import { createBrowserRouter } from "react-router-dom";
import 
    { 
        Bookmark,
        FormLayout,
        Home,
        Login,
        Register,
        RootLayout,
        ViewBlog,
        ProtectedRoute,
        LogedIn,
        ForgotPassword
    } from '../components/links'

export const router = createBrowserRouter([
    {
        path:'/',
        element:<RootLayout/>,
        children:[
            {
                path:'/',
                element:<Home/>
            },
            {
                path:'bookmark',
                element:(
                    <ProtectedRoute>
                        <Bookmark/>
                    </ProtectedRoute>
                )
            },
            {
                path:'blog/:id',
                element:(
                    <ProtectedRoute>
                        <ViewBlog/>
                    </ProtectedRoute>
                )
            }
        ]
    },
    {
        path:'/form',
        element:(<LogedIn><FormLayout/></LogedIn>),
        children:[
            {
                path:'login',
                element:<Login/>
            },
            {
                path:'register',
                element:<Register/>
            },
            {
                path:'forgot-password',
                element:<ForgotPassword/>
            }
        ]
    }
])