import { createBrowserRouter } from "react-router-dom";
import 
    { 
        Bookmark,
        FormLayout,
        Home,
        Login,
        Register,
        RootLayout,
        ViewBlog,
        ProtectedRoute,
        LogedIn,
        ForgotPassword,
        PostEditor,
        BlogPreview,
        Profile,
        BlogEditor,
        VisitProfile
    } from '../components/links'

export const router = createBrowserRouter([
    {
        path:'/',
        element:<RootLayout/>,
        children:[
            {
                path:'/',
                element:<Home/>
            },
            {
                path:'bookmark',
                element:(
                    <ProtectedRoute>
                        <Bookmark/>
                    </ProtectedRoute>
                )
            },
            {
                path:'blog/:id',
                element:(
                    <ProtectedRoute>
                        <ViewBlog/>
                    </ProtectedRoute>
                )
            },
            {
                path:'post/editor/:id',
                element:(
                    <ProtectedRoute>
                        <PostEditor/>
                    </ProtectedRoute>
                )
            },
            {
                path:'blog/preview/:id/:type',
                element:(
                    <ProtectedRoute>
                        <BlogPreview/>
                    </ProtectedRoute>
                )
            },
            {
                path:'profile/:id',
                element:(
                    <ProtectedRoute>
                        <Profile/>
                    </ProtectedRoute>
                )
            },
            {
                path:'blog/editor/:id',
                element:(
                    <ProtectedRoute>
                        <BlogEditor/>
                    </ProtectedRoute>
                )
            },
            {
                path:'visit/profile/:id',
                element:(
                    <ProtectedRoute>
                        <VisitProfile/>
                    </ProtectedRoute>
                )
            }
        ]
    },
    {
        path:'/form',
        element:(
            <LogedIn>
                <FormLayout/>
            </LogedIn>
        ),
        children:[
            {
                path:'login',
                element:<Login/>
            },
            {
                path:'register',
                element:<Register/>
            },
            {
                path:'forgot-password',
                element:<ForgotPassword/>
            }
        ]
    }
])